DELETE http://localhost:3003/api/blogs/68598a94f91f0a4eea3e5811
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMTIzNDUiLCJpZCI6IjY4NTk3NmFiNzkyOTMxYjFmZTZiMWQ1NyIsImlhdCI6MTc1MDcwMjEwMH0.7r0owmqLNvTx7Gen8-7vqCmyaWRJBkeHI0V_Rr0l3z0